name: playx_network
description: playx_network is a Wrapper around Dio that can perform api request with better error handling and easily get the result of any api request.
version: 0.0.4
homepage: https://sourcya.com/
repository: https://github.com/playx-flutter/playx_network
issue_tracker: https://github.com/playx-flutter/playx_network/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:

