name: playx_network
description: playx_network is a Wrapper around Dio that can perform api request with better error handling and easily get the result of any api request.
version: 0.3.0
homepage: https://sourcya.io
repository: https://github.com/playx-flutter/playx_network
issue_tracker: https://github.com/playx-flutter/playx_network/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

topics:
    - playx
    - dio
    - network
    - api

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  sentry_dio: ^8.12.0
  playx_core: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

